export const GET_ALBUMS_INIT = 'GET_ALBUMS_INIT';
export const GET_ALBUMS_LOADING = 'GET_ALBUMS_LOADING';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_ERROR = 'GET_ALBUMS_ERROR';

export const GET_ALBUM_INIT = 'GET_ALBUM_INIT';
export const GET_ALBUM_LOADING = 'GET_ALBUM_LOADING';
export const GET_ALBUM_SUCCESS = 'GET_ALBUM_SUCCESS';
export const GET_ALBUM_ERROR = 'GET_ALBUM_ERROR';

export const GET_ALBUM_PHOTOS_INIT = 'GET_ALBUM_PHOTOS_INIT';
