export const GET_ALBUMS_INIT = 'GET_ALBUMS_INIT';
export const GET_ALBUMS_LOADING = 'GET_ALBUMS_LOADING';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_ERROR = 'GET_ALBUMS_ERROR';
