export const GET_PHOTOS_INIT = 'GET_PHOTOS_INIT';
export const GET_PHOTOS_LOADING = 'GET_PHOTOS_LOADING';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_ERROR = 'GET_PHOTOS_ERROR';

export const GET_PHOTO_INIT = 'GET_PHOTO_INIT';
export const GET_PHOTO_LOADING = 'GET_PHOTO_LOADING';
export const GET_PHOTO_SUCCESS = 'GET_PHOTO_SUCCESS';
export const GET_PHOTO_ERROR = 'GET_PHOTO_ERROR';
